# Generated by Django 2.1.7 on 2019-04-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='server_cpu',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_gpu',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_mem',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_net',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_storage',
        ),
    ]
